Store owner products tab UI
TheSkillGarage/afroshop-admin pull request #1
Opened 2023-11-07 15:28 UTC by EdiongAlexander

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2023-11-10 16:56 UTC, Eshy10 requested changes
@EdiongAlexander lets start from this feedback then i will recheck for the UI. also check for other repeated codes

2023-11-10 16:56 UTC, Eshy10 commented on src/Routes.js
> +        <Route exact path="/dashboard" element={<AdminDashboard />} />
@EdiongAlexander create a page for the overview page

2023-11-10 16:56 UTC, Eshy10 commented on src/components/admin-products/sidebar.jsx
> +
@EdiongAlexander lets reduced repeated code here by mapping

2023-11-10 16:56 UTC, Eshy10 commented on src/pages/App.js
> +        <img src={AfroshopLogo} alt="logo"/>
the overview page can be here

2023-11-10 16:56 UTC, Eshy10 commented on src/components/admin-products/index.jsx
> +
@EdiongAlexander we have a layout component, keep the sidebar and navbar there since it is used in all pages to avoid repeating the code. refer back to afroshop

2023-11-10 16:56 UTC, Eshy10 commented on src/components/admin-products/dashboard.jsx
@EdiongAlexander create a reusable pagination component it is also used in several place. an hooks usePagination

2023-11-14 13:52 UTC, EdiongAlexander commented
I've pushed changes @Eshy10

2023-11-22 12:57 UTC, merged