Store dashborad
TheSkillGarage/afroshop-admin pull request #10
Opened 2023-12-14 15:04 UTC by RatiMathur

### [Please link the Jira ticket that this PR addresses here.]
https://trello.com/c/mmnRTmmU/178-fe-dashboard

## Description
Dashboard and welcome page for afroshop stores is created

## To Test
Goto /welcome and /dashboard to check the UI of pages.

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2023-12-14 17:56 UTC, Eshy10 commented on src/components/dashboard/dashboard.js
> +  const headers = [
@RatiMathur we can keep this in the data folder

2023-12-14 17:56 UTC, Eshy10 commented on src/components/dashboard/dashboard.js
> +            <SummaryCards
@RatiMathur we can map through this to avoid DRY

2023-12-14 17:57 UTC, Eshy10 commented on src/components/dashboard/dashboard.js
> +               <CustomerCard customerImage= {CustomerImage1} customerName= "Paityn Dokidis" customerEmail = "paitynd@gmail.com" numberOrders= "54 orders"/>
@RatiMathur same as this place

2023-12-14 17:58 UTC, Eshy10 commented
@RatiMathur please fix your conflicts

2023-12-14 18:02 UTC, Eshy10 requested changes
@RatiMathur overview page is what you are working on. it should appear when i click on the overview menu on the sidebar so we are using "/" route.

<img width="1184" alt="Screenshot 2023-12-14 at 19 00 27" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/60239486-555e-4057-87c2-b02eeae44b5b">

The dashboard is squashing the sidebar and the content overflows to the right.

<img width="1280" alt="Screenshot 2023-12-14 at 19 00 43" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/9b119fb3-16b0-4a85-a41d-fd6aa8c578ef">

2023-12-14 18:12 UTC, Eshy10 commented
@RatiMathur we can work on other feedbacks and functionality after the provided feedback

2023-12-20 02:50 UTC, Eshy10 commented
@RatiMathur please fix your conflicts

2023-12-20 03:12 UTC, RatiMathur commented
Conflicts resolved
For now User can click on "add my store" button on welcome page to goto dashboard

2023-12-22 16:38 UTC, merged