Edit products: Update product info on table
TheSkillGarage/afroshop-admin pull request #32
Opened 2024-01-29 09:02 UTC by EdiongAlexander

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-01-29 19:02 UTC, ObiTam commented
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/bc77e950-d2fd-4137-b69c-8000d5416874)
the entire header should be clickable and have cursor pointer.

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/badbc048-add2-4294-bc45-240af3d4968e)
please work on the regex. number types shouldn't accept regex. etc. 

Also add errors to the form. 

Submit button should be disabled if 
1  No edit has been made.
2  Errors in the form.

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/5476f8db-e97b-4509-9ff8-8df4298a742c)
add cursor pointer to delete icon.

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/992190e0-ad5d-4a70-b761-867dbd6f0092)
The drag and drop isn't working here.

Confirm from samuel what Save as draft should do. Right now it does nothing. I envisage that it should close the page and create a new draft product with the edited details.

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/7b962cba-80b5-4140-952b-44b4377de158)
Please let's group the products routes together

2024-01-29 19:19 UTC, ObiTam requested changes
Hi Ediong,

The UI looks Amazing. Well done!

I made some functional requests. I also made some requests for optimization of the code. I'll stop here cause its getting a bit lengthy. Please take a look then we can go from there.

Cheers.

2024-01-29 19:19 UTC, ObiTam commented on src/components/edit-products/index.js
> +  const PRODUCT_DATA = useSelector((state) => state.productsData);
let's use camel case for this please.

2024-01-29 19:19 UTC, ObiTam commented on src/redux/action.js
> +export const editProduct = (sku, productInfo, PRODUCT_DATA) => dispatch => {
This should receive the new productInfo and the SKU. 
All the logic should be done in the reducer based on the productData gotten from the previous state. 
This is for encapsulation and abstraction

2024-01-29 19:19 UTC, ObiTam commented on src/components/edit-products/index.js
> +  useEffect(() => {
lets take this out once we're done.

2024-01-29 19:19 UTC, ObiTam commented on src/components/products-changes/index.js
>      setSelectedCategory(newCategory);
I don't think we need selectedCategory and Selected Files. They are just duplicates of what is coming from product info. I think we can take it out.

2024-01-29 19:37 UTC, EdiongAlexander commented on src/components/products-changes/index.js
>      setSelectedCategory(newCategory);
But the category and files can be updated

2024-01-29 19:37 UTC, EdiongAlexander commented on src/components/edit-products/index.js
> +  useEffect(() => {
Okay

2024-02-06 21:44 UTC, ObiTam requested changes
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/2f1658d4-ba98-4dbb-95c9-c555bf8f59d5)
why is it saying required when there is data. why is the error triggering.

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/eba1f257-ad78-430e-b117-85121168477b)

It also doesn't let me submit because of the errors.
I'll take a look at the code soon.

2024-02-08 23:09 UTC, ObiTam commented
Hi Ediong. 
I'd like us to test this out together.
Before then lets make these changes. 

1. There are branch conflicts you should check and resolve.

2. The product changes component should have a local state which all the input components point to. This state is initialised with the product info prop for edit products. For new products this is initialised with a suitable initial object. Ofcourse you can do that basis your name variable. However, I think this name prop should be changed for readability - perhaps edit product and make it be true or false. Think through this and come up with an optimum solution.

3. We render images using a url. when a new image is uploadedd we do not have a url for that image just the raw image data. we can generate a pseudo url for that image on the fly and upload till the backend can generate that url and send it to us. 
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/6f9f7432-0b2a-4d98-8adf-89e7488ca59e)
This image is from the profile tab. you can view for your use.

let us structure our product with images like this 
```
const PRODUCT_DATA = [
    {
        id: "product-1",
        // other product data
        images: [
            {
                url: 'frontend/image', // pseudo url generated on frontend since we have an imageFile attached
                data: imageFile // image file that will be uploaded on the backend
            },
            {
                url: 'backend/image', // actual image url
                data: null // null since image url is on backend already
            },
            // other images
        ]
    },
    // other products
]
```

4. For the Tabs
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/e6d65f1c-7f3c-4712-ba94-1c06bc7a6796)
Let's have a tab state that we start initially as an empty string. If a tab is clicked then we check if tab state is equal to tab clicked. if it is we turn tab to empty string else we turn tab to tab clicked. 

5. Continuing from 2 above. any changes in the product changes component will be made to the local state of the product information. You may have a local state count with change count that is adjusted within the product info state handler that handles changes of the product. This will enable you to change the Submit and Save as Draft to active only if a change has been made. The Product Changes Component performs 3 actions.
-  Cancel will just redirect to the intended new url perhaps the product page. The local state with all changes will be deleted and no changes will be made to the product info saved in redux (simulates the backend).
-  The save as draft will call a function the is passed into the Product changes function. This will take the local state and pass it to the product array in the backend with status draft. (per my understanding). It will only be active if a change has been made.
- Similary, the submit button will only be active if a change has been made and will call a prop function. Depending on if the edit product prop is true or false it will either append to the products in redux (simulates the backend) or edit the adequate product.

6. Regarding treatment of button activity. Changes in product Info can easily be compared. 
```
  const [changes, setChanges] = useState(0)
  const [localData, setData] = useState(reduxData)

  const handleProductInfo = (key, val) => {
    if (localData[key] === reduxData[key] && reduxData[key] !== val) { // local data matches redux data but new value is different
      if (key === 'images') { 
        setChanges(prev => prev + 2) // this will keep image changes permanent
      }
      else {
        setChanges(prev => prev + 1)
      }
    }
    else if (localData[key] !== reduxData[key] && reduxData[key] === val) { // local data doesn't match reduc data but new value does
      if (key !== 'images') {
        setChanges(prev => prev + 1)
      }
    }
    setData((prevData) => ({
      ...prevData,
      [key]: val,
    }))
  }
```
This as above is just an example. Changes  > 0 may then be used to make disable the button or not.

------------------------------------------------------------------------------------
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/de4d24aa-e4f8-45f7-86b0-69507a5cee5b)
what is the use of this?

please check the way the checkout on main afroshop frontend is handled for clarity.
I'm available for any questions. Sorry this is late.

2024-02-15 12:23 UTC, ObiTam commented
@Eshy10 please can we merge this and work on new changes in a new pr.

cc @EdiongAlexander @KaraEno please test

2024-02-15 12:42 UTC, merged