Dashboard and Orders page WIRE UP
TheSkillGarage/afroshop-admin pull request #46
Opened 2024-03-12 11:57 UTC by EdiongAlexander

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-03-14 00:11 UTC, ObiTam commented
@EdiongAlexander Let's make time to go through this together tomorrow.

2024-03-15 16:36 UTC, Eshy10 commented
> @EdiongAlexander Let's make time to go through this together tomorrow.

@EdiongAlexander did you have the meeting with @ObiTam

2024-03-16 22:29 UTC, ObiTam reviewed
Hi Ediong, 

Let's effect these changes then shola will merge. we will fix other things in a new pr. 

Well done.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +    const [selectedYear, setSelectedYear] = useState(2024);
Let's make this into a single object with a single function that adjusts the values based on the key.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +    const [years, setYears] = useState([
we can't have these years hardcoded.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +        const calculatePercentageChanges = () => {
Let's extract all the functions into a script in the utils folder.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +        const calculatePercentageChanges = () => {
Let's extract all the functions into a script in the utils folder.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +                    <SelectDropdown name="summary" options={years} placeholder="2024" handleSelectedYear={handleSelectedYear} color="green" />
We can't hardcode this.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/cards-section.js
> +                    cardNumber={totalSales.toFixed(2)}
Let's create a function for this. it takes in a figure and returns it with the $ sign and to 2 significant figures.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/dashboard.js
> +    const getTopProducts = () => {
Let's move all these functions out of the file to the utils folder

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/dashboard.js
> +      ordersData.forEach(data => {
extract this into a function that takes in ordersData and returns all you need from it.

2024-03-16 22:29 UTC, ObiTam commented on src/components/dashboard/lineChart.js
> +    const formatDate = (date, selectedYear) => {
Again extract this into a utils folder.

2024-03-16 22:29 UTC, ObiTam commented on src/components/orders/view-orders.js
> +                                        <p>{date.toLocaleDateString('en-GB')}</p>
why great britain. we need to do us/canada

2024-03-16 22:29 UTC, ObiTam commented on src/components/orders/view-orders.js
> +                        {/* <Search handleSearch={handleSearch} name="view-orders" DATA={order.products} handleFilterObject={handleFilterObject} /> */}
why's this commented out

2024-03-16 22:29 UTC, ObiTam commented on src/components/overview/index.js
> +        dispatch(getOrdersData(storeData.id, token));
this should be storeData?.id. it will throw an error if no orders.
Also this calls and all calls should be in the layout. not in this component.

2024-03-16 22:29 UTC, ObiTam commented on src/data/dashboardTimeOptions.js
>  const SELECT_OPTIONS = [
this can't be hardcoded. 
from the list of options get the min date and the max year is the present year.

2024-03-16 22:29 UTC, ObiTam commented on src/redux/action.js
> +export const getOrdersData = (storeID, token) => async (dispatch) => {
test storeID first.

2024-03-16 22:29 UTC, ObiTam commented on src/redux/action.js
> +export const getStoreData = (userID, token) => async (dispatch) => {
test userID first.

2024-03-18 08:19 UTC, EdiongAlexander commented on src/components/dashboard/cards-section.js
> +    const [selectedYear, setSelectedYear] = useState(2024);
What are you talking about here?

2024-03-18 18:51 UTC, ObiTam commented
what happens if I go to a page 

/view-order/:orderID

and :orderID is not a valid order?

2024-03-21 23:16 UTC, ObiTam requested changes
Calculate totals and Top Products customers should be in a single file. call it OrderSummaryFunctions.js

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/24448a46-30c6-4749-b2db-597ba39cb1f5)
there were no orders this week. write it there don't leave it blank.

You would need to wireup update orders too. 

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/3b389123-ec94-42ce-a6f0-6213eb2a3566)
this search isn't working. is it searching by name?


![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/fed726b3-ac6e-4c8b-b2df-f394ed7db448)


![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/23965eee-cd2a-4e2b-bc3b-d846ec7af38a)

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/98851264-ec83-411f-a9a6-a8790885bac5)
add something like "No Orders have been delivered" don't leave it empty.

let's handle the orders page in a different pr. 

Well done Ediong. Sorry this is so long

2024-03-21 23:16 UTC, ObiTam commented on src/components/orders/view-orders.js
> +        if (!order) {
There should be a page for this not just a redirect. Speak to Samuel. Also we need to have clear instructions about how an order changes from pending to delivered to whatever. It's a bit too easy right now.

2024-03-21 23:16 UTC, ObiTam commented on src/components/orders/index.js
> +            {ordersData.length > 0 ?
ordersData === null or ordersData?.length > 0

2024-03-21 23:16 UTC, ObiTam commented on src/components/orders/orders-dashboard.js
> +        <TableFooter
all the pagination data should be in the footer. i don't see any reaso why prevPage e.t.c is being handled here.

2024-04-04 19:39 UTC, ObiTam approved these changes
LGTM

@Eshy10 please take a look.

2024-04-05 16:49 UTC, Eshy10 commented
@EdiongAlexander update the summary section to empty state
<img width="510" alt="Screenshot 2024-04-05 at 17 48 36" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/2234b34f-757b-486b-b03a-41b3d575cd88">

2024-04-05 16:51 UTC, Eshy10 commented
> @EdiongAlexander update the summary section to empty state <img alt="Screenshot 2024-04-05 at 17 48 36" width="510" src="https://private-user-images.githubusercontent.com/52670459/320079423-2234b34f-757b-486b-b03a-41b3d575cd88.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTIzMzYwNzksIm5iZiI6MTcxMjMzNTc3OSwicGF0aCI6Ii81MjY3MDQ1OS8zMjAwNzk0MjMtMjIzNGIzNGYtNzU3Yi00ODZiLWIwM2EtNDFiM2Q1NzVjZDg4LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MDUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDA1VDE2NDkzOVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWY3M2ZiODEwNTQ3MzI0YjU2ZTZlNDVjMDI0MzAxYTRiNTI5ZjM5MzBlZWMyZjQyMmIxMDkxMjFmNTYzODlhY2UmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.mdB5n5lL_A9EMUabyeVEvZErGzY4O4MhvyTLzs9CbJo">

let's have $0 instead of $0.00
<img width="191" alt="Screenshot 2024-04-05 at 17 50 19" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/0effa358-c6dc-41a7-b054-9258be346515">

2024-04-08 12:48 UTC, Eshy10 commented on src/utils/OrderSummaryFunctions.js
> +        const decThirtyFirst = new Date(Number(selectedYear), 11, 31);
@EdiongAlexander can you explain why we are sing decThirtyFist here

2024-04-08 16:53 UTC, merged