Password wireup
TheSkillGarage/afroshop-admin pull request #47
Opened 2024-03-13 15:19 UTC by KaraEno

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-03-14 00:03 UTC, ObiTam requested changes
Looks Good Kara. 

I haven't tested if it works yet. I just took a look at the code. Let's make the slight changes and make it easy for the person wiring up the profile to work.

2024-03-14 00:03 UTC, ObiTam commented on src/components/profile/index.js
> +        <form onSubmit={ currentTab !== "Profile" ? handleSubmit(onSubmit) : null}>
Haha. you're simultaneously breaking the profile tab while wiring up the password tab. 

You should use the existing framework. this won't fly. 

You don't have to use the onSubmit function while commenting out the onClick. The onclick will work perfectly and you will call your function there.

2024-03-14 00:03 UTC, ObiTam commented on src/components/profile/index.js
> +                // onClick={(event) => {
reconsider this choice.

2024-03-14 00:03 UTC, ObiTam commented on src/redux/action.js
> +export const postRequest = (url, data, token) => {
set a default for token.

2024-03-16 22:32 UTC, ObiTam commented on src/components/profile/index.js
> +      toast.error(`${error}`, {
error or error.message

2024-03-16 22:33 UTC, ObiTam requested changes
Please look into all the requested changes. 
after you handle resolve the conversation

2024-03-16 22:50 UTC, KaraEno commented on src/redux/action.js
> +export const postRequest = (url, data, token) => {
@ObiTam Can you point out what you mean here?

2024-03-16 22:52 UTC, KaraEno commented on src/components/profile/index.js
> +                // onClick={(event) => {
I reconsidered this, using an Onclick instead of onSubmit does not give the needed result, so I updated the onSubmit condition instead. @ObiTam

2024-03-17 19:53 UTC, ObiTam commented on src/redux/action.js
> +export const postRequest = (url, data, token) => {
not all post requests are authenticated and as such we won't always pass in token. set a default value to null.

2024-03-17 21:14 UTC, ObiTam commented
@Eshy10 Please check this.

2024-03-18 14:27 UTC, Eshy10 commented on src/components/profile/index.js
> +        throw new Error(responseData?.error?.message);
@KaraEno we use toast to show the error here

2024-03-18 14:28 UTC, Eshy10 requested changes
@KaraEno once a user is done changing the password  you can close this form.

<img width="999" alt="Screenshot 2024-03-18 at 15 26 24" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/a9279677-5d58-406d-baa8-b9b41922608c">

2024-03-19 14:46 UTC, Eshy10 commented
@KaraEno update on this?

2024-03-19 16:32 UTC, Eshy10 commented on src/components/auth/forms/login.js
> +        if (userData?.role?.name) {
@KaraEno revert this

2024-03-19 16:34 UTC, Eshy10 commented on src/components/profile/index.js
> +        //   `${
@KaraEno remove unused code

2024-03-19 16:45 UTC, Eshy10 commented on src/components/auth/forms/login.js
> +        if (userData?.role?.name) {
@KaraEno

2024-03-19 16:47 UTC, merged