Feat/blossom/store wire up
TheSkillGarage/afroshop-admin pull request #51
Opened 2024-03-21 23:13 UTC by Blossom1-chike

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]
store wireup with backend

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-03-22 01:36 UTC, ObiTam requested changes
![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/9f4e86c0-39f0-4fb5-b8d2-e17b5adc52b6)
opening times is not wired up. discuss with samuel

Merge latest changes from main and deal with conflicts

Did you work on create store? for new admins?

2024-03-22 01:36 UTC, ObiTam commented on src/components/auth/forms/ResetPassword.js
> +console.log(success, responseData)
remove console.log

2024-03-22 01:36 UTC, ObiTam commented on src/components/profile/index.js
> +  const updateStoreInfo = async () => {
we don't need this function. put it directly inot handle profile form submit

2024-03-22 01:36 UTC, ObiTam commented on src/components/profile/index.js
> +  const updateStoreInfo = async () => {
there's no need for a sepereate button to upload an image. 

Store image update isn't even working. 

Do it this way instead. when an image is uploaded for an update you load it into data. 
when a user clicks save you first check to see if data is not null fo the image. if it is then you upload it and await the upload. if it doesn't work you set an error that we couldn't upload the image. if it works you then use that image id in your update store call to update the image.

2024-03-25 10:42 UTC, Blossom1-chike commented on src/components/profile/index.js
> +  const updateStoreInfo = async () => {
done

2024-03-25 10:42 UTC, Blossom1-chike commented on src/components/auth/forms/ResetPassword.js
> +console.log(success, responseData)
done

2024-03-25 11:12 UTC, ObiTam requested changes
the delete button doesn't work 

![image](https://github.com/TheSkillGarage/afroshop-admin/assets/45231955/83058204-b374-4230-b549-9c59da803322)
it should remove the image there but it shouldn't allow you to submit  without uploading a new image. 

if you're adding a toast for image is uploading which I don't think is necessary then you need to add an image upload successful and an image upload error. I'd rather there be one toast for successful store details upload and failed store details upload. 

Well done. just a little more.

2024-03-25 11:12 UTC, ObiTam commented on src/utils/index.js
> +    toast.info(`⏳ uploading image.....`, { autoClose: 2000 });
why are you throwing an error in the catch statememend

2024-03-25 11:14 UTC, ObiTam commented
> ![image](https://private-user-images.githubusercontent.com/45231955/315850795-9f4e86c0-39f0-4fb5-b8d2-e17b5adc52b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjU0MjcsIm5iZiI6MTcxMTM2NTEyNywicGF0aCI6Ii80NTIzMTk1NS8zMTU4NTA3OTUtOWY0ZTg2YzAtMzlmMC00ZmI1LWI4ZDItZTE3YjVhZGM1MmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDUwNjIzYWZjYjY1MGQ0N2RhMWMzYzViZjhhNjYxMGIxMDBiZmRjMDA2NWVlNDlmM2FkZTk4ZDFhNDZlZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZAkCsXYfAohdz_IDwAgwWJ0R09GGv_p_NVKH9zk5GU) opening times is not wired up. discuss with samuel
> 
> Merge latest changes from main and deal with conflicts
> 
> Did you work on create store? for new admins?

@Blossom1-chike  any update?

2024-03-26 14:06 UTC, Blossom1-chike commented
> > ![image](https://private-user-images.githubusercontent.com/45231955/315850795-9f4e86c0-39f0-4fb5-b8d2-e17b5adc52b6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTEzNjU0MjcsIm5iZiI6MTcxMTM2NTEyNywicGF0aCI6Ii80NTIzMTk1NS8zMTU4NTA3OTUtOWY0ZTg2YzAtMzlmMC00ZmI1LWI4ZDItZTE3YjVhZGM1MmI2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzI1VDExMTIwN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTliMDUwNjIzYWZjYjY1MGQ0N2RhMWMzYzViZjhhNjYxMGIxMDBiZmRjMDA2NWVlNDlmM2FkZTk4ZDFhNDZlZTcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.HZAkCsXYfAohdz_IDwAgwWJ0R09GGv_p_NVKH9zk5GU) opening times is not wired up. discuss with samuel
> > Merge latest changes from main and deal with conflicts
> > Did you work on create store? for new admins?
> 
> @Blossom1-chike any update?

i told sameuel, he hasn't replied on slack

2024-03-27 22:15 UTC, ObiTam approved these changes
@Eshy10 Please review.

2024-04-02 04:00 UTC, Eshy10 commented
@Blossom1-chike i am a new store owner but i already see a profile picture with the option to delete it, it should show the default profile picture which is the placeholder.
<img width="231" alt="Screenshot 2024-04-02 at 04 55 16" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/ec08f36e-aece-44a5-8423-98c78a5deb5f">

- when i try to add an holiday i get an error

<img width="1272" alt="Screenshot 2024-04-02 at 04 57 33" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/f0576eca-1e0e-4a03-94f3-bbea8f453bf4">

<img width="639" alt="Screenshot 2024-04-02 at 04 57 47" src="https://github.com/TheSkillGarage/afroshop-admin/assets/52670459/350642f3-dab4-4c9e-8aca-f1ef0af9998e">

2024-04-13 01:59 UTC, ObiTam commented
Hi @Blossom1-chike Please resolve the conflicts then i'll take a look.

2024-04-17 18:52 UTC, ObiTam approved these changes

2024-04-18 14:06 UTC, Eshy10 commented
we are moving the fix i noticed to another pr @Blossom1-chike @ObiTam

2024-04-18 14:06 UTC, merged