refactor: add SKU field in the form to create product
TheSkillGarage/afroshop-admin pull request #82
Opened 2024-09-03 16:52 UTC by Blossom1-chike

### [Please link the Jira ticket that this PR addresses here.]

## Description
[Please put a description of the changes this branch introduces here.]
add form field for SKU when creating a product
add SKU to the payload sent to the api when creating a product

## To Test
[Please write instructions for testing your changes locally here. Include any data setup, tests, urls, and potential snags in local testing.]

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
[Any screenshots of the changes can go here.]

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-09-04 15:19 UTC, ObiTam requested changes
Hi Blossom, 

I think the choice for custom SKUs should be at store level. If a Store chooses to use custom SKUs then all products must have custom SKUs alternatively the SKUs will be user generated.  

That means we would add a toggle on the store profile info that is not editable. "use Custom SKU". 

@Eshy10 what do you think?

Please refactor.

2024-09-04 15:19 UTC, ObiTam commented on src/components/products-changes/index.js
> +                      patternValue={"^AFR-[a-zA-Z0-9]+"}
Hi blossom, 

It doesn't have to start with AFR. Lets just add a minimum limit of 5 characters - alphanumeric.

2024-09-05 15:28 UTC, Eshy10 commented
> Hi Blossom,
> 
> I think the choice for custom SKUs should be at store level. If a Store chooses to use custom SKUs then all products must have custom SKUs alternatively the SKUs will be user generated.
> 
> That means we would add a toggle on the store profile info that is not editable. "use Custom SKU".
> 
> @Eshy10 what do you think?
> 
> Please refactor.

@ObiTam this works

2024-09-06 14:47 UTC, Blossom1-chike commented
> Hi Blossom,
> 
> I think the choice for custom SKUs should be at store level. If a Store chooses to use custom SKUs then all products must have custom SKUs alternatively the SKUs will be user generated.
> 
> That means we would add a toggle on the store profile info that is not editable. "use Custom SKU".
> 
> @Eshy10 what do you think?
> 
> Please refactor.

this sounds like the option to use custom SKUs is accross the store and not the product, so for a store that already has products with generated SKUs and i want to use custom SKUs, what happens?

2024-09-06 19:44 UTC, ObiTam commented
> > Hi Blossom,
> > I think the choice for custom SKUs should be at store level. If a Store chooses to use custom SKUs then all products must have custom SKUs alternatively the SKUs will be user generated.
> > That means we would add a toggle on the store profile info that is not editable. "use Custom SKU".
> > @Eshy10 what do you think?
> > Please refactor.
> 
> this sounds like the option to use custom SKUs is accross the store and not the product, so for a store that already has products with generated SKUs and i want to use custom SKUs, what happens? @ObiTam

lack of custom skus falls back to generated sku.

2024-09-09 20:07 UTC, ObiTam approved these changes

2024-09-09 20:09 UTC, ObiTam commented
@Eshy10 @Davidosky007 
This is pending till review of backend PR.

2024-09-11 18:26 UTC, merged