Products database UI & wire-up
TheSkillGarage/afroshop-admin pull request #83
Opened 2024-09-04 12:46 UTC by EdiongAlexander

### [Trello](https://trello.com/c/6TJ85gPb/353-building-a-library-of-all-the-products-for-adding-them-to-stores-need-ui-from-samuel)]

## Description
- Add products from database

## To Test
Go to add new products and select database entry

## Checklist
- [ ] I have looked over the diffs.
- [ ] There are no errors/failing tests from my changes on this branch.
- [ ] I have requested a review on this PR and re-assigned the Jira ticket.

## Screenshots
![image](https://github.com/user-attachments/assets/5856276b-f7b9-4064-9fe1-174c43aaddc3)

## Extra Notes
[Please include any extra notes you may have about the changes here.]

2024-09-06 21:01 UTC, ObiTam requested changes
1. In the product database selectore sort by name and use the array index for selection. default to 0.
2. 
![image](https://github.com/user-attachments/assets/4a515293-e907-4a9c-b4e3-929e0b92ae88)
remove the div within custom scrollbar. - it has no use.
3.
![image](https://github.com/user-attachments/assets/e5c02526-f37a-4589-9641-723874e23619)
your filters are disconnected. here i am trying to filter within proteinous foods for something with "my" instead it filters product database for "my"
You should have a state filters that maps the filtering of product database. that way i can execute multiple filters at a time - by category and name.
4.
I do not think that this is the optimal way to achieve the product database.
no changes need to be made to any file within product-changes, It should all end at addprduct/index.js.
you need a state to switch between manual and database input.
by default product info is initialized with 
```
  const useProductInfo = {
    productCategory: "",
    category: "",
    name: "",
    availability: "0",
    price: 0,
    discount: 0,
    description: "",
    images: [],
    taxable: false,
    unitWeightInGrams: 0,
    pricingType: "per Item",
    measurementUnit: "",
  };
```
add a useEffect that monitors tab and if there is a database input. if a database product has been selected then assign its values to product info. that's all.

2024-09-09 15:34 UTC, EdiongAlexander commented on src/components/auth/forms/login.js
> +        if (userData?.role?.name ) {
I didn't

2024-09-13 01:31 UTC, ObiTam reviewed
Hi Kara,

I made some changes to the product modal. 

please see my comments and lets try to get the save as draft and save button to work. tahanks

2024-09-22 20:39 UTC, ObiTam commented
closing in favor of other PR

2024-09-22 20:39 UTC, closed without merging